name: Continuous Delivery
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  deliver:
    name: Build Delivery
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup golang
      uses: actions/setup-go@v4
      with:
        go-version: stable
    - name: Build app
      run: go build -v cmd/main.go
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: go-api-app
        include-hidden-files: true
        path: |
          main
          .env.example
  docker:
    name: Upload to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: luizmatias/go-api:latest
  discord-alert:
    name: Run Discord Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}